### ISSUE TITLE
Individual Markdown file per Class

### ISSUE THREAD

**Issue by jaredcatkinson** [jaime-olivares/xmldoc2md#2]
Thanks for this module! I'm trying to add documentation of my library's public API and this project has been excellent.

How difficult would it be to create a unique markdown file per class? I'm not familiar with XSL format/capabilities.

**Comment by jaredcatkinson** [comment]
I ended up just adding logic to the PowerShell script to break every Type into its own Markdown file.

**Comment by gibsonjoshua55** [comment]
Any chance you still have that script?
